[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.27.0", features = ["approx"] }
rand = "0.8.4"
extend = "1.2.0"
rayon = "1.10.0"
approx = "0.5.1"
